### PR TITLE
Update pt_BR.lang

### PR DESCRIPTION
**Pull request by Ar97x**

### CODE REVIEW

**Comment by Ar97x** [comment]
Wait a little to merge, I'll pull some other commits.

**Comment by Ar97x** [comment]
How do I pull other commits into this one?

**Comment by IceDragon200** [comment]
Ouch, sorry about that:
do a `git pull --rebase origin development` on the command line
followed by a `git push your_remote your_branch -f` to force push over the existing branch

**Comment by Ar97x** [comment]
Figured it out before, if I did it right I still don't know lol.

**Comment by IceDragon200** [comment]
@Ar97x You wouldn't mind translating the latest Ice Cream variant, I just added Watermelon

**Comment by IceDragon200** [comment]
@Ar97x Hmm, conflicts are still present, did you rebase and force push?

**Comment by Ar97x** [comment]
Are they? Looks like everything passed.

**Comment by IceDragon200** [comment]
@Ar97x Hold off for a few minutes, lemme smash it locally

And that's how you rekt it :D

Also, please tag your commits from now on

**Comment by Ar97x** [comment]
Oh I'll remember to tag them next time. I'll tackle the modded bee boxes later (damn, there are so many!).

**Comment by IceDragon200** [comment]
@Ar97x Get ready to cry then, we'll be adding more for 2.6

**Comment by Ar97x** [comment]
I've checked the Forestry repo and they have pt_Br translations, so it
won't be so painful.

**Pull request merged**
