### PR TITLE
Forestry 4 reintegration (Testers Wanted)

### PR DESCRIPTION
**Pull request by IceDragon200**
This should solve 50% of #48
## What does this do?

Restores compatibility with [Forestry](https://github.com/ForestryMC/ForestryMC), the parts that aren't covered by the Forestry Growthcraft plugin.
### Latest

[Build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_forestry-reintegration-build3.jar)
### Old

[Build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_forestry-reintegration-build2.jar)
[Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_forestry-reintegration-build1.jar)
[Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_forestry-reintegration-build0.jar)

### CODE REVIEW

**Comment by Yulife** [comment]
Is this for Forestry 3 or 4?

**Comment by IceDragon200** [comment]
@Yulife: Should be 4, I worked from the latest ForestryAPI

**Comment by Yulife** [comment]
Ahhh, nice :wink:

**Comment by labpaw** [comment]
Not sure why you did this. Forestry now has Growthcraft integration built-in [since this commit](https://github.com/ForestryMC/ForestryMC/commit/bcd97662b273e775ff6dac6985b34979b5e5892e). Did you read discussion in #48?
The only thing that should be done is:
"It looks like that bit could just be uncommented, none of those names have changed as far as I can see.

By that bit, I mean these: https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/bees/GrowthCraftBees.java#L225-L243

You can remove these lines
https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/bees/GrowthCraftBees.java#L244-L257
and uncomment that section (assuming those calls haven't changed in Growthcraft internal, no idea what that actually does)"

**Comment by IceDragon200** [comment]
@Adaptivity Ah, I overlooked that, my apologies, I was in a trance updating left and right :(

**Comment by IceDragon200** [comment]
@Adaptivity I just read the forestry code, its missing the backpack entries for grapes ~~and grapeSeeds~~, that's about the only thing missing from that side

**Comment by labpaw** [comment]
Well, then grapes can be added on Forestry side (I can inform devs about it). It's really better to keep as much integration as possible on Forestry side since it's has a lot of supported mods. Is ForestryModuleBase.java still needed on GC side? It's seems to have duplicated code which is already available in Forestry. Maybe it's better to move ForestryModule.java code into ForestryModuleBase.java and maybe rename it's to just ForestryModule? Since it will contain just few lines of code.

**Comment by IceDragon200** [comment]
@Adaptivity The base class was used by the other modules, that's why its an abstract class, the original code had each module extend the base class, and do their registrations there, instead of having it in a centralized location, it included helper methods to avoid extra conditional code (like the original did by checking for different managers), now, its no longer needed

**Comment by labpaw** [comment]
Yes, this is what I wanted to say. Maybe you just remove base class then? Should be good I guess.

**Comment by IceDragon200** [comment]
@Adaptivity Removed :+1:

**Comment by IceDragon200** [comment]
@Adaptivity If everything is ok, I'll merge this

**Comment by labpaw** [comment]
I guess so. I dunno how bees integration works anyway. What maybeAddBee means? Growthcraft adds new bees or what?

**Comment by IceDragon200** [comment]
@Adaptivity We take the forestry bees and add it to our own bees registry for use in the Bee Box, `maybe-AddBee` means "if the item is valid (not null in this case), add it as a bee, otherwise do nothing"

``` java
if (item != null) BeeRegistry.instance().addBee(item);
```

**Comment by labpaw** [comment]
Oh, I got it.

**Pull request merged**
