### PR TITLE
WIP: Milk Module

### LINKED ISSUE #131: Error Reports
I'm opening this for eventual error reports that might come from the forum and for anyone that needs help with bugs. If you can help, feel free to coment here. This is the first one:

```
[22:47:03] [Client thread/DEBUG] [MCFrames/]: Enabling mod MCFrames
 [22:47:03] [Client thread/DEBUG] [FML/]: Found translations in ForgeRelocation-0.0.1.4-universal.jar [en_US]
 [22:47:03] [Client thread/DEBUG] [ForgeRelocation/]: Enabling mod ForgeRelocation
 [22:47:03] [Client thread/DEBUG] [FML/]: Found translations in ForgeRelocation-0.0.1.4-universal.jar [en_US]
 [22:47:03] [Client thread/DEBUG] [RelocationFMP/]: Enabling mod RelocationFMP
 [22:47:03] [Client thread/DEBUG] [MrTJPCoreMod/]: Enabling mod MrTJPCoreMod
 [22:47:03] [Client thread/DEBUG] [redgear_core/]: Enabling mod redgear_core
 [22:47:03] [Client thread/TRACE] [FML/]: Verifying mod requirements are satisfied
 [22:47:03] [Client thread/TRACE] [FML/]: All mod requirements are satisfied
 [22:47:03] [Client thread/TRACE] [FML/]: Sorting mods into an ordered list
 [22:47:03] [Client thread/ERROR] [FML/]: Mod Sorting failed.
 [22:47:03] [Client thread/ERROR] [FML/]: Visting node APIContainer{CoFHAPI:1.0}
 [22:47:03] [Client thread/ERROR] [FML/]: Current sorted list : [Dummy Container (BeforeAll) @2108554981, Wrapped{mcp}, Wrapped{FML}, Wrapped{Forge}, Wrapped{Dummy Container (null) @1062826950}, Wrapped{Aroma1997Core}, Wrapped{CodeChickenCore}, Wrapped{Dummy Container (null) @1800288316}, Wrapped{ivtoolkit}, Wrapped{MCVanillaTweaks}, Wrapped{MobiusCore}, Wrapped{NotEnoughItems}, Wrapped{OpenComputers|Core}, Wrapped{Dummy Container (null) @231818377}, Wrapped{TubesCore}, Wrapped{OpenModsCore}, Wrapped{<CoFH ASM>}, FMLMod:debug{1.0}, Dummy Container (Before) @1335446611]
 [22:47:03] [Client thread/ERROR] [FML/]: Visited set for this node : [APIContainer{CoFHAPI:1.0}, Wrapped{MCVanillaTweaks}, Wrapped{<CoFH ASM>}, Wrapped{CodeChickenCore}, Dummy Container (BeforeAll) @2108554981, Dummy Container (AfterAll) @750349296, Dummy Container (Before) @1335446611, Wrapped{Dummy Container (null) @1062826950}, Wrapped{MobiusCore}, Wrapped{ivtoolkit}, FMLMod:BuildCraft|Core{7.1.12}, FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2}, Wrapped{Dummy Container (null) @1800288316}, Wrapped{Forge}, Wrapped{Dummy Container (null) @231818377}, Wrapped{mcp}, Wrapped{OpenComputers|Core}, Wrapped{OpenModsCore}, Wrapped{Aroma1997Core}, FMLMod:CoFHCore{1.7.10R3.0.3}, Wrapped{FML}, FMLMod:BuildCraft|Builders{7.1.12}, Dummy Container (After) @1062496828, Wrapped{NotEnoughItems}, FMLMod:debug{1.0}, Wrapped{TubesCore}]
 [22:47:03] [Client thread/ERROR] [FML/]: Explored node set : [Wrapped{Aroma1997Core}, Wrapped{MCVanillaTweaks}, Wrapped{FML}, Wrapped{<CoFH ASM>}, Wrapped{CodeChickenCore}, Dummy Container (BeforeAll) @2108554981, Dummy Container (Before) @1335446611, Wrapped{Dummy Container (null) @1062826950}, Wrapped{MobiusCore}, Wrapped{NotEnoughItems}, Wrapped{ivtoolkit}, Wrapped{Dummy Container (null) @1800288316}, Wrapped{Forge}, Wrapped{Dummy Container (null) @231818377}, FMLMod:debug{1.0}, Wrapped{mcp}, Wrapped{OpenComputers|Core}, Wrapped{OpenModsCore}, Wrapped{TubesCore}]
 [22:47:03] [Client thread/ERROR] [FML/]: Likely cycle is in : [APIContainer{CoFHAPI:1.0}, Dummy Container (AfterAll) @750349296, FMLMod:BuildCraft|Core{7.1.12}, FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2}, FMLMod:CoFHCore{1.7.10R3.0.3}, FMLMod:BuildCraft|Builders{7.1.12}, Dummy Container (After) @1062496828]
 [22:47:03] [Client thread/ERROR] [FML/]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
 [22:47:03] [Client thread/ERROR] [FML/]: The first mod in the cycle is APIContainer{CoFHAPI:1.0}
 [22:47:03] [Client thread/ERROR] [FML/]: The mod cycle involves
 [22:47:03] [Client thread/ERROR] [FML/]: APIContainer{CoFHAPI:1.0} : before: [redgear_core, emashercore, emasherdefense, gascraft, eng_toolbox, EnderTech, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory, BuildCraft|Compat, minechem, Railcraft, StevesAddons, funkylocomotion, FloodLights, CoFHCore, MalCore, fluxedfeederunit, Forestry, enhancedportals, ExtraUtilities, simplyjetpacks, IC2NuclearControl, RouterReborn, EnderIO, bcadditions, Mariculture, MariTech], after: [CoFHCore]
 [22:47:03] [Client thread/ERROR] [FML/]: Dummy Container (AfterAll) @750349296 : before: [], after: []
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:BuildCraft|Core{7.1.12} : before: [], after: [Forge@[10.13.2.1236,)]
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2} : before: [], after: [Forge@[10.13.2.1208,), BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Factory, BuildCraft|Builders, LiquidXP]
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:CoFHCore{1.7.10R3.0.3} : before: [], after: [Forge@[10.13.3.1448,10.14)]
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:BuildCraft|Builders{7.1.12} : before: [], after: [BuildCraft|Core@7.1.12]
 [22:47:03] [Client thread/ERROR] [FML/]: Dummy Container (After) @1062496828 : before: [], after: []
 [22:47:03] [Client thread/ERROR] [FML/]: The full error
 cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
 at cpw.mods.fml.common.Loader.sortModList(Loader.java:272) [Loader.class:?]
 at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) [Loader.class:?]
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
 at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
 [22:47:03] [Client thread/DEBUG] [FML/]: Mod sorting data
 [22:47:03] [Client thread/DEBUG] [FML/]: Additional-Buildcraft-Objects(Additional Buildcraft Objects:MC1.7.10-BC7release3.0.2): ABO-MC1.7.10-BC7-release3.0.2.jar (required-after:Forge@[10.13.2.1208,);required-after:BuildCraft|Transport;required-after:BuildCraft|Energy;required-after:BuildCraft|Silicon;required-after:BuildCraft|Factory;required-after:BuildCraft|Builders;after:LiquidXP)
 [22:47:03] [Client thread/DEBUG] [FML/]: additionalpipes(Additional Pipes:4.7.0): additionalpipes-4.7.0.jar (after:BuildCraft|Transport[7.1.5,);after:BuildCraft|Silicon;after:BuildCraft|Transport;after:BuildCraft|Factory;after:LogisticsPipes)
 [22:47:03] [Client thread/DEBUG] [FML/]: AdvancedMachines(IC2 Advanced Machines Addon:1.1.6): AdvancedMachinesAS-1.7.10.jar (required-after:IC2@2.2.775)
 [22:47:03] [Client thread/DEBUG] [FML/]: AdvancedSolarPanel(Advanced Solar Panels:1.7.10-3.5.1): AdvancedSolarPanel-1.7.10-3.5.1.jar (required-after:IC2; after:gregtech_addon; after:AppliedEnergistics;)
 [22:47:03] [Client thread/DEBUG] [FML/]: ae2stuff(AE2 Stuff:0.5.0.56): ae2stuff-0.5.0.56-mc1.7.10.jar (required-after:appliedenergistics2;required-after:bdlib@[1.9.2.104,))
 [22:47:03] [Client thread/DEBUG] [FML/]: AgriCraft(AgriCraft:1.7.10-1.4.1): AgriCraft-1.7.10-1.4.1-1.7.10.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareAutomation(Ancient Warfare Automation:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare;after:CoFHCore;after:BuildCraft|Core)
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfare(Ancient Warfare Core:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareNEIPlugin(Ancient Warfare NEI Plugin:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare;after:NotEnoughItems)
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareNpc(Ancient Warfare NPCs:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare)
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareStructure(Ancient Warfare Structures:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare)
 [22:47:03] [Client thread/DEBUG] [FML/]: aobd(Another One Bites The Dust:2.8.4): AOBD-2.8.4.jar (required-after:Forge@[10.13.4.1448,);after:*)
 [22:47:03] [Client thread/DEBUG] [FML/]: appliedenergistics2(Applied Energistics 2:rv2-stable-10): appliedenergistics2-rv2-stable-10.jar (after:appliedenergistics2-core;required-after:Forge@[10.13.2.1291,))
 [22:47:03] [Client thread/DEBUG] [FML/]: Aroma1997CoreHelper(Aroma1997Core|Helper:1.0.2.15): Aroma1997Core-1.7.10-1.0.2.15.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: AromaBackup(AromaBackup:0.0.0.5): AromaBackup-1.7.10-0.0.0.5.jar (required-after:Aroma1997Core)
 [22:47:03] [Client thread/DEBUG] [FML/]: Artifacts(Artifacts:1.1.2): Artifacts-1.1.2.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: baublelicious(Baublelicious:1.0.4): Baublelicious-1.7.10-1.0.5.jar (required-after:Baubles@[1.0.1.4,);)
 [22:47:03] [Client thread/DEBUG] [FML/]: bcapiHolder(bcapiHolder:1.0): bcapi-6.0.x.jar (after:BuildCraft|Core;after:Forestry;after:railcraft;before:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: bdlib(BD Lib:1.9.3.107): bdlib-1.9.3.107-mc1.7.10.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: BetterTitleScreen(Better Title Screen:1.7.10-1.1): BetterTitleScreen-1.7.10-1.1.jar (required-after:Forge@[10.12.2.1147,))
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioCraft(BiblioCraft:1.10.5): BiblioCraft[v1.10.6][MC1.7.10].jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioWoodsBoP(BiblioWoods Biomes O'Plenty Edition:1.9): BiblioWoods[BiomesOPlenty][v1.9].jar (after:BiblioCraft;after:BiomesOPlenty)
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioWoodsForestry(BiblioWoods Forestry Edition:1.7): BiblioWoods[Forestry][v1.7].jar (after:BiblioCraft;after:Forestry)
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioWoodsNatura(BiblioWoods Natura Edition:1.5): BiblioWoods[Natura][v1.5].jar (after:BiblioCraft;after:Natura)
 [22:47:03] [Client thread/DEBUG] [FML/]: BigReactors(Big Reactors:0.4.3A): BigReactors-0.4.3A.jar (required-after:Forge@[10.13.2.1291,);required-after:CoFHCore;after:ThermalExpansion)
 [22:47:03] [Client thread/DEBUG] [FML/]: Botany(Botany:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: BinnieCore(Binnie Core:2.0-pre14): binnie-mods-2.0-pre14.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: ExtraBees(Extra Bees:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: ExtraTrees(Extra Trees:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: Genetics(Genetics:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: BiomesOPlenty(Biomes O' Plenty:2.1.0): BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar (after:Natura; required-after:Forge@[10.12.2.1147,))
 [
```

### PR DESCRIPTION
**Pull request by IceDragon200**
## What is this?

It be the [Milk Module](https://github.com/Alatyami/Growthcraft-1.7/wiki/Growthcraft-Milk-%28Concept%29). 
### Latest

**2016-02-20 @ 20:05:59 EST** [2.5.0 - Build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.5.0/growthcraft-1.7.10-2.5.0-complete_grcmilk-build3.jar)

> #### Changes
> - Cheese Vat now respects heat source blocks
> - Cheese Vat can now create Ricotta Cheese (use 5 buckets of Whey instead of Milk)
> - Hanging Curds, and Cheese Blocks are now limited to a stack size of 1
> - Waxing works (Cheddar, Montery)
> - Cheese Press can press Dried Curds (a bit iffy, but it works, place the curd in the press and then right click while holding an item (I may just add 2 inventory slots instead of relying on 1 to fix this))
> - Unwaxed cheeses will not age.
> - Right clicking a Cheese Block will pull one slice from it
> - Cheese Block's are no longer rendered as models, but are done via TESR, the inventory render remains unchanged for now.
#### Irks
- Still relying on Forestry for Milk.
### Old

**2016-02-18 @ 14:17:49 EST** [2.5.0 - Build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.5.0/growthcraft-1.7.10-2.5.0-complete_grcmilk-build2.jar)

> #### Changes
> - Rebased against latest development

**2016-02-15 @ 19:27:59 EST** [2.5.0 - Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.5.0/growthcraft-1.7.10-2.5.0-complete_grcmilk-build1.jar)

> #### Changes
> - Cheese Vat process is now complete, but a bit clunky
> - Curds SHOULD dry over time (they have fixed time currently)
> - Next step is the Cheese Press

**2016-02-15 @ 14:39:03 EST** [2.5.0 - Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.5.0/growthcraft-1.7.10-2.5.0-complete_grcmilk-build0.jar)

> #### Changes
> - Rebased against development, this adds Apple Core 1.3.0 support and Forestry Integration

**2016-02-14 @ 22:45:48 EST** [2.4.0 - Build 18](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build18.jar)

> #### Changes
> - #207 

**2016-02-14 @ 22:17:24 EST** [2.4.0 - Build 17](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build17.jar)

> #### Changes
> - More work on the Cheese Vat, recipes should kinda work, they should produce their corresponding "cheese" fluid, which is currently not coloured, because I forgot :scream:,
>   Suggested recipes should produce cheese fluids.
>   Next update will include cheese cloth interaction and actual curd draining (hopefully).
> ##### EG.
> - Create a Cheese Vat by crafting a Brew Kettle (again)
> - Slap it down over a recognized heat source (I think it currently works without it...)
> - Pour 5 buckets of milk in
> - Pour 1 bottle of rennet
> - Whack the Vat with a Sword (right click.)
> - Use a bucket and remove the Whey fluid
> - Follow cheese recipes (or just throw 1 salt and 1 orange dye and make Cheddar, that works too :cake:)
> - Not sure what happens from there, your millage may vary. ┐(￣ヮ￣)┌
> ##### What `should` happen later.
> - Using a cheese cloth to pick up the cheese curds
> - Hanging it up
> - Special: if you used poisoned wine or cider in the recipe it should also poison the cheese.
>   **2016-02-13 @ 15:43:29 EST** [2.4.0 - Build 16](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build16.jar)
> - FiIxed recipes

**2016-02-13 @ 12:17:46 EST** [2.4.0 - Build 15](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build15.jar)

> - Added some crafting recipes

**2016-02-11 @ 16:48:29 EST** [2.4.0 - Build 14](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build14.jar)

> - Rebased development

**2016-02-02 @ 17:35:40 EST** [2.4.0 - Build 13](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build13.jar)

> - Added config option for removing all booze effects except tipsy
> - Added config option for hiding `POISONED` booze tags and their effects

**2016-01-31 @ 22:48:31 EST** [2.4.0 - Build 12](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build12.jar)

> - Added Bees Wax items (no recipes yet)
> - Butter Churn now works! Just add a bucket of Cream and churn away until it stops

**2016-01-31 @ 18:15:26 EST** [2.4.0 - Build 11](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build11.jar)

> - Stomach drop rate and amount are configurrable
> - All User API recipes have been updated
> - Added Brewing Recipe for Rennet using Stomach

**2016-01-31 @ 15:41:59 EST** [2.4.0 - Build 10](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build10.jar)

> - Rice block texture fix #131
> - Hanging curds now produce whey fluids
> - Calves (Baby cows) should now drop 2~4 stomachs, have fun ~~butchering~~ harvesting

**2016-01-30 @ 01:00:02 EST** [2.4.0 - Build 9](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build9.jar)

> Bees User API for adding bees and flowers

**2016-01-29 @ 23:??:02 EST** [2.4.0 - Build 8](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build8.jar)

> Fishtrap User API, Cheese Vat fluid rendering (this was sitting on my computer for days now)

**2016-01-22 @ 00:11:52 EST** [2.4.0 - Build 7](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build7.jar)

> Bug fixes, bug fixes, BUG FIXES

**2016-01-18 @ 00:13:37 EST** [2.4.0 - Build 6](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build6.jar)

> Not really a Milk build, but a Cellar thing, added an option for toggling the Discard Button

**2016-01-17 @ 23:37:10 EST** [2.4.0 - Build 5](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build5.jar)

> Pancheon gets an updated model, fixed a handful of bugs in cellar (really this should have been done in development, but _shrug_), started work on the Cheese Vat

**2016-01-17 @ 19:11:08 EST** [2.4.0 - Build 4](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build4.jar)

> Lots of refactoring to get base classes for use in the Milk module, the core and cellar modules have been hit with a shovel over the head. On other news, Pancheon now works, if you have Forestry installed you can also use it's milk :+1: 

[2.4.0 - Build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build3.jar)

> Removed test animations, added toggled states for Butter Churn and Cheese Press

[2.4.0 - Build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build2.jar)

> Cheese blocks, rendering, types and aging

[2.4.0 - Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build1.jar)

> Added fluids and their blocks, added animations, and a few other core tweaks

[2.4.0 - Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.4.0/growthcraft-1.7.10-2.4.0-complete_grcmilk-build0.jar)

### CODE REVIEW

**Comment by Sunconure11** [comment]
When you can, you might want to add a feature so that if another mod adds a milk fluid, this mod's milk fluid will be turned off in favor of that one, but, said fluid can be used in place of growthcraft's milk fluid. Many mods add milk fluids.

**Comment by Ar97x** [comment]
Are you guys thinking about milk processing, like UHT treatment and so? Or
is it just a name change for what would be dairy module?

**Comment by IceDragon200** [comment]
@Sunconure11, @PitchBright Looks like its time to upload that design document...

EDIT: [Design Docs](https://github.com/GrowthcraftCE/Growthcraft-DesignDocs)

**Comment by Sunconure11** [comment]
Not sure if this is either a bug or something you have not come around to yet, but kumis and its variants have no name ingame.

**Comment by PitchBright** [comment]
That stuff would be removed as it has no use/purpose at this point in time.

**Comment by IceDragon200** [comment]
@Sunconure11, @PitchBright  : Its from the original `dairy` module (before it was fleshed out), we could work it back into the module as an extension, but I haven't moved/removed them yet

**Comment by Sunconure11** [comment]
I'll push out a texture for an unaged Gorgonzola. The current one irks me a bit. I'll do a more accurate one Thursday.

**Comment by Sunconure11** [comment]
gorgonzola_unaged

**Comment by Sunconure11** [comment]
I tried to see if I could push it to this request, but, I am having a bit of a hard time doing so.

**Comment by Sunconure11** [comment]
I was also going to change the names of a few folders reserved for future modules.

**Comment by Sunconure11** [comment]
I think I got it.

**Comment by PitchBright** [comment]
So, disregard the texture you uploaded tonight then? Or was that "aged" that you uploaded?

**Comment by PitchBright** [comment]
Doesn't matter… I'll just send all 3 stages at once right now. Takes like 3 minutes to do it.

**Comment by Sunconure11** [comment]
The stomach has no name in build 10.

**Comment by IceDragon200** [comment]
@Sunconure11 It does now

**Comment by Sunconure11** [comment]
Any plans to add recipes for the functional devices (such as the churn)?

**Comment by PitchBright** [comment]
We'll get him something, Sunny.

**Comment by PitchBright** [comment]
Scratch that Sunny, you and I forgot that they were in the design document already. I'm sure he'll add 'em when he gets there.

**Comment by IceDragon200** [comment]
@PitchBright  @Sunconure11 I was gonna poke you guys about some of the recipes,
you see the Cauldron is already used to create the Brew Kettle, we could create a Cheese Vat from a Brew Kettle (though aesthetic wise, its like the player whacked the legs off the Brew Kettle and slapped them on top to make up the full block height).

There was something else I forgot to ask, oh right!
Starter Culture!

I was thinking of moving the starter culture recipe 

in order to get Culture Jar's to accept heat, I'll end up complicating the yeast registry.

``` json
// This is a single entry
{
  "biome_names": [],
  "biome_types": [TRUNCATED_FOR_EXAMPLE],
  "requires_heat": 1.0,
  "item": { TRUNCATED }
}
```

It doesn't look bad so far, but how do you handle cases where the item will require heat, but must be present in EVERY biome without copy pasting everywhere, and how about handling cases where heat would kill the yeast?
And how about fluid specific formations? (Skim Milk), and ones that rely on certain fluid tags (that are not present outside of Growthcraft remind you.).

While I was planning to add a heat component to the Jar, I realized how complicated it would make the poor thing.

So instead I opt to move the recipe to the Brew Kettle, I've already provisioned it to accept NO residue, and I think no output fluid, I could be wrong on the latter.

WDYT?

**Comment by PitchBright** [comment]
Is Cauldron > Kettle a shapeless recipe? If so… it can go shaped and we can do something like, if the cauldron is in the 1st crafting grid slot.. it becomes Kettle, if it's in the 2nd slot it becomes Vat.

Thoughts?

**Comment by Sunconure11** [comment]
While me and Pitch had sent you recipes in the past, I will post the ones I had thought of briefly before realizing that we had sent you recipes:

> Butter churn:
> 
> Null Lever Null
> Any_plank Stick Any_Plank
> Any_Plank Any_Plank Any_Plank
> 
> Pancheon:
> 
> Null Null Null
> Clay_Ball Any_Dye Clay_Ball
> Clay_Ball Clay_Ball Clay_Ball
> 
> Cheese Vat: (probably needs a better recipe)
> 
> Null Null Null
> Iron Kettle Iron
> Iron Iron Iron
> 
> Beeswax:
> 
> Boil empty honeycombs in kettle (waste product is slumgum, which IRL can be used to attract bee swarms, maybe it can be used to obtain more bees by leaving it on flowers or something; or maybe place it on the side of an apiary to increase the rate at which bees are produced) (https://en.wikipedia.org/wiki/Slumgum)
> 
> Colored beeswax:
> 
> Dye beeswax with red or black dye
> 
> Cheese Cloth:
> 
> 8 string occupying all slots but the middle slot
> 
> Hanging Curds:
> 
> Null Stick Null
> Cheese_Cloth Stick Cheese_Cloth
> Cheese_Cloth Cheese_Cloth Cheese_Cloth

Notes: Beeswax should be oredictionary compatible with other wax items from other mods

**Comment by PitchBright** [comment]
Let's just roll with the recipes in the design document. No need to add extra noise here. If there's an issue with any of them, we can revisit it prior to release after thorough testing.

**Comment by IceDragon200** [comment]
~~Gonna be doing some gnarly rebasing, NOBODY TOUCH THIS BRANCH OR DEVELOPMENT PLS.~~

Remind me NEVER again to use a feature branch for development, I'm sure I lost some commits, SOMEWHERE

**Comment by IceDragon200** [comment]
New Build added (14), this build was created from the freshly rebased branch, and MAY be unstable.

**Comment by Sunconure11** [comment]
When does thistle come into play, seeing as work on the cheese-making code has begun.

**Comment by Sunconure11** [comment]
Also, curd fluid has no name.

**Comment by Sunconure11** [comment]
Cheese blocks should not be a valid fuel source.

**Comment by Sunconure11** [comment]
Chocolate ice cream is using cocoa blocks, not cocoa items.

**Comment by Sunconure11** [comment]
We should put up some screencaps of the milk module since its nearing completion. Here is one I took while testing to see if the cheese working process was working fine.

https://www.dropbox.com/s/41p4c4n6pi06zw0/Screenshot%202016-02-21%2011.25.36.png?dl=0

**Pull request merged**
