### PR TITLE
Applecore integration

### PR DESCRIPTION
**Pull request by IceDragon200**
For #26
- [x] Apples
- [x] Hops
- [x] Grapes
- [x] Rice

Is there anything else I missed?

### CODE REVIEW

**Comment by IceDragon200** [comment]
Link to the Jar if anyone wants to test: [Growthcraft-AppleCoreIntegration](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/growthcraft-2.1.0.jar)

**Comment by PitchBright** [comment]
I get this crash when trying to bonemeal a grape seedling, and also when I just let the seedling grow on its own: http://pastebin.com/1jFgcUqu

**Comment by PitchBright** [comment]
Hops crash: http://pastebin.com/2CRxWAEZ

**Comment by PitchBright** [comment]
Apples on Apple Trees: http://pastebin.com/dyDh8PaR

**Comment by IceDragon200** [comment]
@PitchBright D; Ah the horror, I'm sure I didn't screw up...
I'm pretty sure I didn't screw up...
I compiled against AppleCore 1.2.1, unfortunately I can't find a client release for it, which might be your problem (you're running 1.1.0)

I've opened an issue https://github.com/squeek502/AppleCore/issues/31

**Comment by squeek502** [comment]
Sorry about the confusion. Note: The only thing you'd need to do to make it compatible with AppleCore 1.1.0 is use the AppleCoreAPI.dispatcher.announcePlantGrowth version without the previousMetadata parameter [here](https://github.com/alatyami/Growthcraft-1.7/pull/27/files#diff-da2bd36b2cb81b90e4587354c040b396R38).

**Comment by IceDragon200** [comment]
@squeek502: I'd also need to downgrade the api to 1.1.0 right? (_me points at build.gradle dependencies_)

**Comment by squeek502** [comment]
You wouldn't _need_ to, the no previousMetadata method is simply deprecated in post-1.1.0 API versions.

**Comment by squeek502** [comment]
If you wanted to, though, you could change the `dependencies` in the build.gradle to `compile "applecore:AppleCore:1.7.10-1.1.0:api"`.

**Comment by IceDragon200** [comment]
Yeah, just to be safe, also everyone can head over to #29 for testing and such

**Comment by PitchBright** [comment]
I no longer experience those crashes, when I use "growthcraft-2.2.1-with-applecore-fix.jar". So I think you've got it fixed up!

I originally came across the GrowthCraft/AppleCore issue when configuring a new mod called "BiomeCrops" that controls crop growth-by-biome. BiomesCrops doesn't recognize these fixed-up GrowthCraft blocks as crops it can control anymore, so I'll report that over there.. and hopefully it's a simple little thing on that end that doesn't need to come back around this way.

Thanks guys!

**Pull request merged**
