### PR TITLE
Fixed Village Structure spawning

### PR DESCRIPTION
**Pull request by IceDragon200**
This should fix village structures spawning with invalid blocks in them.

Overall the changes are: adding a overload of `drawSchema` that takes an offset and all structures using the `SchemaToVillage` format fill their base layer with grass, as well as clearing the bounding box with air blocks.
### Latest

[Build3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-2.2.2-complete_with_village_fixes-build3.jar)
### Old

[Build2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-2.2.2-complete_with_village_fixes-build2.jar)
[Build1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-2.2.2-complete_with_village_fixes-build1.jar)

### CODE REVIEW

**Comment by Ar97x** [comment]
I'm trying to get a final model for the Bees build, I'll finish it soon and
see with forum people, then we can merge this.

**Comment by Sunconure11** [comment]
Once the apiaries are finished, should I merge this?

**Comment by Ar97x** [comment]
After a few testing should be okay for you to merge this.

**Comment by Alatyami** [comment]
I haven't had a  chance to test yet. Anyone else do testing yet?

**Comment by IceDragon200** [comment]
@Ar97x @alatyami @Sunconure11 : I'll prepare a quick test build before I leave for business

EDIT: Added link in the op

**Comment by Sunconure11** [comment]
I won't be able to test this build, but, has anyone tested to see if it works?

**Comment by Ar97x** [comment]
I can try, this week will be hard and timeless, but I think I can take some time. As soon as IceDragon release the build I'll run some tests. I'll try to release the new apiary this thursday (almost sure this time)

-------- Mensagem Original --------
De:Joseph Caleb Jones notifications@github.com
Enviado em:Tue, 08 Sep 2015 22:38:03 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Cc:Ar97x vdiehl97@gmail.com
Assunto:Re: [Growthcraft-1.7] Fixed Village Structure spawning (#79)

**Comment by IceDragon200** [comment]
@Ar97x Build's in the top post :octocat:

**Comment by Ar97x** [comment]
I forgot. I've tested it and it seems that only the bamboo yard needs some
improvements. I think you forgot to put the grass layer behind the
structure, as you can see in the screenshot of it above the ocean. I've
found that all of our structures (except Bamboo Yard) adapt to every biome
it is. I want to suggest you to look at the regular building platform and
those we made. The vanilla buildings go all the way down, and ours only
have a layer of support. It looks kinda weird to me. Screenshots here:
https://www.dropbox.com/sh/t7nxtq0gv30g5vl/AADDT_hpKTpArAKeCX2b5GtBa?dl=0

**Comment by IceDragon200** [comment]
@Ar97x I missed some ground clearing code in the originals, also Bamboo cannot and will not adapt, since its not a vanilla block, nothing I can do about that unless you tell me what mod makes these changes (or is it vanilla D:)

**Comment by Sunconure11** [comment]
I will see about merging this after all the tweaks are finished. For now, I cannot do much, my computer is away for an upgrade, and I need to start the model for the still as soon as I get the PC back

**Comment by Ar97x** [comment]
@IceDragon200 I don't mind if the Bamboo Yard doesn't change, it's the most original build of GC. I'll have some time to finish the apiary tomorrow, and with the remaning fixes we should be able to merge it this week. What will we have on the next release, besides the village structures fix?

**Comment by Ar97x** [comment]
Do you think we should add something to fishtrap module? A guy on the forum gave me an interesting idea.

**Comment by IceDragon200** [comment]
Man, that was a workout, having to poke around WorldGenerators, the good news is: NO MORE SAPLING HACKS :D
The bad news: I COPIED CODE ACROSS 2 CLASSES.

@Ar97x 
Check top post for new build (Build2), as for fishtrap, I dunno, make something the least I can do is implement it, not sure how it would work World Gen wise yet, but I'd figure it out.

**Comment by Ar97x** [comment]
I'll check it later and try something for fishtraps tomorrow. If you don't want, we discard it.

**Comment by Ar97x** [comment]
I'll test it later and think about something for fishtrap tomorrow. If you
don't want, we discard it.

**Comment by Ar97x** [comment]
Hey guys I just want to let you know that I couldn't make the Apiary yet, I got sick last week and stayed on bed all the weekend, I'm recovering now and had to get back to classes today. But it'll be released tomorrow, sorry for the postponement.

**Comment by Ar97x** [comment]
Got the apiary ready this afternoon, link: https://www.dropbox.com/sh/0w3og3mso33kyjd/AAC434_VQiNKh0G5HXOgfOJHa?dl=0 And about the fishtrap thing, I don't think it is really necessary, @alatyami can we do a poll on forum to see if people want a building on the villages based on the fishtrap?

**Comment by IceDragon200** [comment]
@Ar97x Ok, added the new design, try out the latest build (Build3 as of this writing)

**Comment by Alatyami** [comment]
I'll draft up an issue for surveying for a fish trap structure and post it
to the forum.

**Comment by Sunconure11** [comment]
So, I'm guessing this is safe to merge now? Or do I have to wait on the fish trap structure?

**Comment by Alatyami** [comment]
Unless it can be done before the 30th, lets push Fishtrap to the next
release.

**Comment by Sunconure11** [comment]
Hm, what if the new structure is a wharf?

**Comment by Alatyami** [comment]
I'd like to see that, makes sense. I do not know of very many mods that
have a warf structure.

**Comment by Ar97x** [comment]
Great idea. I'll try something for it at night.

**Comment by Ar97x** [comment]
I made a sketch of what I understand by wharf, and I think it's pretty decent. If you have something in mind, send me a image to base on. https://www.dropbox.com/sh/ckjyafxohbciilc/AACiotip26XL3Exe_MDLp8Jla?dl=0
I'll share this on the forum thread, so I can get more ideas and feedback.

**Comment by Ar97x** [comment]
One guy gave me an idea to make the little wharf spawn randomly, and I thought about replacing the witch hut on swamps, or just making it spawn randomly, can you do it @IceDragon200 ?

**Comment by Sunconure11** [comment]
I think Wharfs spawning randomly around beaches would be a good idea. Maybe around modded beach biomes as well.

**Comment by IceDragon200** [comment]
@Ar97x, @Sunconure11 I think I'll do the wharf as a separate PR, since this one is for fixing the awkward structure generation.

Sorry about the late response, I caught a cold from playing too much pokemon (I kid you not)

**Comment by IceDragon200** [comment]
@alatyami I think we can merge this, since I'll be doing Warfs for the next release

**Comment by Sunconure11** [comment]
Ready to merge?

**Pull request merged**
