### PR TITLE
Thaumcraft (Re-)Integration (Testers Wanted)

### PR DESCRIPTION
**Pull request by IceDragon200**
This should solve 50% of #48
## What does this do?

Restores compatibility with [Thaumcraft](https://github.com/Azanor/thaumcraft).
## Downloads

Builds **MAY** require Buildcraft to work correctly, don't quote me on that one, not sure how this interface stuff works in Java yet.
### Latest

[Build 5 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build5.jar)
### Old

[Build 4 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build4.jar)
[Build 3 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build3.jar)
[Build 2 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build2.jar)
[Build 1 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build1.jar)
[Build 0 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build0.jar)

[Build 4 - 2.2.2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_thaumcraft-reintegration-build4.jar)
[Build 3 - 2.2.2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_thaumcraft-reintegration-build3.jar)
[Build 2 - 2.2.2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_thaumcraft-reintegration-build2.jar)
[Build 1 - 2.2.2 - Includes Thaumcraft API](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_thaumcraft-reintegration-build1.jar)
[Build 0 - 2.2.2 - Includes Thaumcraft API](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_thaumcraft-reintegration-build0.jar)

### CODE REVIEW

**Comment by labpaw** [comment]
You shouldn't include Thaumcraft api in the Growthcraft .jar. This will cause a lot of issues. An example how it should be done: https://github.com/CovertJaguar/Railcraft/pull/349

**Comment by spannerman79** [comment]
I agree @Adaptivity.  This is why I am a little worried about testing this @IceDragon200.  One other mod dev has a bad habit of including other mod's API files in their own API mod which breaks worlds and other mods.the moment there is an update.

**Comment by IceDragon200** [comment]
@spannerman79 @Adaptivity 
Fixed, (after slapping javadoc, gradle and the entire build process; telling them for the 100th time not to include thaumcraft)

**Comment by ghost** [comment]
i can test out thaumcraft. i have latest available version of both i am interested in both of these mods and in fact i have made thaumcraft aspects for most growthcraft components using minetweaker 3

**Comment by ghost** [comment]
here is my complete list of aspects using Minetweaker 3 + Modtweaker 2 

http://pastebin.com/0Rr4wNik

I have manually toiled at it to make it perfect. Even all potions and buckets are supported. newly added liquids will also be supported working on it next.

**Comment by ghost** [comment]
you don't even need thaumcraft api. aspects are simply NBT tags something like this

 {x, y, z, Aspects:[ {amount:1, key:"herba"} , {amount:2, key:"aer"} ], a, b, c }

add similar tags into all Growthcraft already existing NBT Tags and Thaumcraft aspects will be compatible out of the box

**Comment by IceDragon200** [comment]
@trollworkout I'd prefer to use the official API, so we get compile time warnings/errors instead of magical (no pun intended) failures during runtime. 

That aside, thank you for the help, I'll add these after I address a few other issues

Also you wouldn't mind doing the fluid blocks as well?

**Comment by IceDragon200** [comment]
@trollworkout What is the motivation behind using "lux" for the booze?

**Comment by spannerman79** [comment]
> using "lux" for the booze?

lux is illumination, focused on light sources or items/fluids that create light.  I would assume using booze to create a light source (like a torch) but I don't see or I don't know of any other mod that can use booze in that way (so far)

**Comment by IceDragon200** [comment]
@spannerman79 None of our booze are flammable, neither do they emit light, which is why seeing lux on the list stopped me from going any further with the changes

@trollworkout The Beebox and Fishtrap have too many aspects as well, 5+, they're base materials are wood and string at maximum, but yet none of those aspects are present (cloth for the fishtrap and arbor for both)

**Comment by spannerman79** [comment]
> The Fishtrap

_Maybe_ Limus (big maybe for that one - the slim ball needed to create the  1x lead) but for sure Arbor and cloth

> The Beebox

**Only** Arbor

**Comment by ghost** [comment]
@IceDragon200  is luxuria not lux . luxuria is an aspect added by forbidden magic addon and  it luxury or lust or desire. i was thinking about drunkedness . however!  i have updated and changed all the alcohol to use forbidden magic gula instead which is consumption, over indulgence.

edit: this new pastebin is updated for the new buckets  

http://pastebin.com/quy7yJaM

the aim is to make the aspects as compatible as possible . if you don't have forbidden magic installed having gula 1 is ignored but all other aspects still work. 

the way thaumcraft works is it takes what it understands and compiles a database. if you misspell something or you don't have the addon to support it those aspects is fine. will still work. have tested this myself.

**Comment by spannerman79** [comment]
> the aim is to make the aspects as compatible as possible . if you don't have forbidden magic installed having gula 1 is ignored but all other aspects still work.

The point (i assume) for this issue that was raised by @IceDragon200 was to test Thaumcraft reintegration.  Not to test other mods (at this time)  Doing so would mean further complicating matters for this request made by @IceDragon200 

Forbidden Magic API can be added later once this commit has been finalized and merged in as complete.

**Comment by ghost** [comment]
@IceDragon200  sure. i am open to suggestions and changes and ideas. i want to have growthcraft compatible with thaumcraft out of the box ideally. 

i had to make these aspects myself so i kinda made it up as i went along based on what thaumcraft has already done.  thaumcraft believe it or not actually changes only the base items/blocks and most compound blocks are multiplied by the base items/blocks they are made with . there are a bunch of exceptions but that's generally the case.  

note how young versions of all brews are simply water + bucket  . bucket is metal + emptiness . i noticed thaumcraft does this will all buckets + buckets with liquids inside.  so i followed suit.

**Comment by ghost** [comment]
@IceDragon200  simply ignore gula and fames aspects .. that  removes all forbidden magic addon. that's it.

forbidden magic adds the 7 deadly sins only 2 of which apply to growthcraft. desire hunger FAMES and over consumption greed GULA.

**Comment by ghost** [comment]
@IceDragon200 

minetweaker3 + modtweaker2 script for Growthcraft thaum aspects (choose 1):
thaumcraft + forbidden magic 7 deadly sins aspects http://pastebin.com/quy7yJaM
just thaumcraft (no addons) http://pastebin.com/yhp5fCRR

both updated to the latest community growthcraft version

feel free to get back at me to test out thaumcraft aspects if you add support for them when you do . 

edit: apple sapling has been changed to 2 arbor 1 herba.. seems all saplings in the game added by thaumcraft are like this. so i did the same.  & all bee boxes and bee related stuff has been updated to make more sense based on rest of thaumcraft. bee box is emptynes and wood. bee hive is stickiness emptiness and order. full honey comb is order and stickiness and empty honeycomb is order and emptiness. etc is just a basic guidelines. playing with these settings i found it quite integrated with rest of thaumcraft.

**Comment by IceDragon200** [comment]
@trollworkout: I've applied the changes, just waiting for dropbox to stop crapping itself and upload the latest builds -.-;

**Comment by ghost** [comment]
@IceDragon200  awesome :) when you ready send the jar over or maybe i can wait until full release and i can test it out 4 you. i got a test world where i researched everything so i will know right away. i tend to go in creative 1 item at a time. i;ll even test out the new fluids you introduced since 3. 
once his works and is good   perhaps you can add the forbidden magic  aspects as well. is the only thaum addon that applies to growthcraft.

**Comment by IceDragon200** [comment]
@trollworkout You can test it out right now, just scroll back to the top and look under Downloads, 

or 

if you're like me and hate scrolling

[Build 3 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build3.jar)

**Comment by ghost** [comment]
@IceDragon200  off the bat i noticed you made apple seeds (apple core) TREE 1 and PLANT 1 . most seeds in the game are 1 PLANT .

**Comment by IceDragon200** [comment]
BAAAAAH, I felt I missed somethin, ah well, compile a list of problem items/blocks and I'll fix them

**Comment by ghost** [comment]
@IceDragon200  wait hold on..i will test all of them give you a report sir :)

**Comment by ghost** [comment]
@IceDragon200  disregard the comment above

Onigiri -  should be 1 (not 11) PERDITIO (entropy)
Grapes -  should be 1 (not 11) MESSIS (crop)
all brews + buckets + liquids - should have 1 (not 11) AQUA (water)

brew kettle - add 21 METALLUM (metal)
barrel - 18 METALLUM (metal)
fruit press - add 3 METALLUM (metal)
in the original thaumcraft anything made with metal ingots has metal property x   how many ingots it used (each ingot is calculated as 3 METALLUM). every item does this. since the above objects use metal they need to have that. 
honey - 1 (not 11) LIMUS (stickiness)

honeycomb - 1 (not 11) LUCRUM (want, possesion)
this one is actually a forbidden magic aspect you added by accident. probably forgot to remove it from my script. however, seems to work fine :)  maybe you should add the other ones as well. i am going to test this again soon just thaum + growthcraft see the effect it has having the addon aspects. from my experience thaum already knows the aspect but it doesn't use it in the game. 

all the bee boxes don't have any aspects. each one should be TREE  4 and EMPTINESS  

all other ones are fine ;)

**Comment by IceDragon200** [comment]
`LUCRUM` is an actual Thaumcraft Aspect

``` java
public static final Aspect GREED = new Aspect("lucrum",0xe6be44, new Aspect[] {MAN, HUNGER});
```

All those `11`s were in the text so don't blame me :sob:

**Comment by ghost** [comment]
@IceDragon200 i think all of them are thaumcraft aspects from the API even from addons :) sorry my bad about the 11s. i will change my script too. ahaha. OOPS. 

edit: when i fixed the script and removed all the forbidden magic ones the 1 from the extra aspects got added to the previous making 11 haha sorry

**Comment by ghost** [comment]
@IceDragon200  GREED i only used in thaumcraft forbidden magic addon. the api knows about it. see if you find FAMES hunger and GULA consumption there. and if you do follow the proper script i had first. second script i automated removed all the aspects and it created 11s where forbidden magic ones got removed.

**Comment by IceDragon200** [comment]
@trollworkout  https://github.com/Azanor/thaumcraft-api/blob/master/aspects/Aspect.java#L141-L198

**Comment by ghost** [comment]
@IceDragon200  sorry my fault.

convert all 11s to 1s and that fixes most issues :)

GREED =  golden or precious things: diamonds, gold, and honey (cause is golden) and precious .

**Comment by ghost** [comment]
@IceDragon200 

public static final Aspect HUNGER = new Aspect("fames",0x9a0305, new Aspect[] {LIFE, VOID});
this one is default thaumcraft and can also be added 

change all 11s to 1s and add the following:

(in addition to whatever they currently have)
Growthcraft|Bees:grc.honeyComb:1 = add FAMES 1
Growthcraft|Bees:grc.honeyJar = add FAMES 1
Growthcraft|Grapes:grc.grapes = add FAMES 1
Growthcraft|Rice:grc.riceBall= add FAMES 1

That will fix all issues and make it compatible with all thaumcraft aspects (no addons) 

and add aspects to all different bee boxes TREE 4 and EMPTY 1

**Comment by IceDragon200** [comment]
@trollworkout Should the buckets have `21 venenum`, or should that be 2?

**Comment by ghost** [comment]
@IceDragon200  2 venenum. all brews and buckets should be venenum 2. cause alcohol is a bit poison tipsy but also good for you :)

**Comment by IceDragon200** [comment]
@trollworkout New [Build 4 - 2.3.1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build4.jar), give this one a twirl :D I wanna merge this tonight (today, tomorrow, this morning, depending on which side of the planet your on)

Give it some time to upload, I'm having a crappy internet day

**Comment by ghost** [comment]
@IceDragon200  aight im gonna check it out now :)

**Comment by ghost** [comment]
@IceDragon200  error 404 :/ ah  ill wait a bit

**Comment by IceDragon200** [comment]
@trollworkout Try now

**Comment by ghost** [comment]
@IceDragon200  all is good :+1: 

still missing the bee box aspects and the fluid aspects . this is because my script didn't have them as i made this for an older version and updated it to new version but didn't add the new things yet. i will have to add the new stuff. essentially the liquids are same as buckets but no metal or emptiness. all young is aqua 1 and all fermented is aqua 1 venenum 2. and all bee boxes should be arbor 4 and emptiness 1. 

hops:
mods.thaumcraft.Aspects.set(<Growthcraft|Hops:grc.hopAleFluid.0 - aqua 1
mods.thaumcraft.Aspects.set(<Growthcraft|Hops:grc.hopAleFluid.4 - aqua 1
mods.thaumcraft.Aspects.set(<Growthcraft|Hops:grc.hopAleFluid.1 - aqua 1 venenum 2
mods.thaumcraft.Aspects.set(<Growthcraft|Hops:grc.hopAleFluid.2 - aqua 1 venenum 2
mods.thaumcraft.Aspects.set(<Growthcraft|Hops:grc.hopAleFluid.3 - aqua 1 venenum 2

mead:
Growthcraft|Bees:grc.honeyMeadFluid.0 - aqua 1
Growthcraft|Bees:grc.honeyMeadFluid.1 - aqua 1 venenum 2
Growthcraft|Bees:grc.honeyMeadFluid.2 - aqua 1 venenum 2
Growthcraft|Bees:grc.honeyMeadFluid.3 - aqua 1 venenum 2
... all other same aspects as mead (wine, cider, sake) 

Growthcraft|Bees:grc.beeBox - arbor 4 vacuos 1
Growthcraft|Bees:grc.beeBox:1 - arbor 4 vacuos 1
Growthcraft|Bees:grc.beeBox:2 - arbor 4 vacuos 1
Growthcraft|Bees:grc.beeBox:3 - arbor 4 vacuos 1
Growthcraft|Bees:grc.beeBox:4 - arbor 4 vacuos 1
Growthcraft|Bees:grc.beeBox:5 - arbor 4 vacuos 1

looking good  tho. thanks :)

**Comment by ghost** [comment]
@IceDragon200  what's malice bee box? malice tree?? i dont know what to give malice. vacuos 1 + ??? if is  a tree arbor 4 if is a stone terra 2  instead 

edit: seems to be made from something that is not added yet. maybe leave this 1 for later :D

**Comment by IceDragon200** [comment]
@trollworkout Malice Bee Box is for https://github.com/Alatyami/Growthcraft-1.7/pull/118
You don't need to worry about it for now, as its inaccessible by default, they are made from a non-flammable wood, I still haven't figured out what to do with the box, ultimately it does BAD THINGS TO YOUR BEES (or it could be bad in a good way?, I have no idea, when the nether module is finished we'll see).

**Comment by IceDragon200** [comment]
@trollworkout This should be the last [build](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_thaumcraft-reintegration-build5.jar) right, right?

**Comment by ghost** [comment]
@IceDragon200  yes. i m checking right now

**Comment by ghost** [comment]
@IceDragon200  all good :+1:

**Comment by IceDragon200** [comment]
ONWARDS TO MERGE CITY!

EDIT: Damn it me, get ur sh*t together!

**Comment by ghost** [comment]
noice.. thaumcraft aspects  fully supported by this mod now . thank you sir.

**Pull request merged**
