### PR TITLE
WIP: Nether Module

### PR DESCRIPTION
**Pull request by IceDragon200**
I wanted to do the desert module, but the Nether had better docs and most of the textures were complete anyway :cry:
## What is this?

It be the [Nether Module](https://github.com/Alatyami/Growthcraft-1.7/wiki/Growthcraft-Nether-%28Concept%29), scary plants lurk in this module, everything is either gonna burn you or... well kill ya, its dangerous to go alone, take this
### Latest

**2016-02-16 @ 14:36:30 EST** [2.5.0 - Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.5.0/growthcraft-1.7.10-2.5.0-complete_grcnether-build1.jar)

> #### Changes
> - Rebuilt because of local branch issues
### Old

**2016-02-16 @ 14:34:36 EST** [2.5.0 - Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.5.0/growthcraft-1.7.10-2.5.0-complete_grcnether-build0.jar)

> #### Changes
> - Rebased against latest development

[2.3.1 - Build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_grcnether-build3.jar)
[2.3.1 - Build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_grcnether-build2.jar)
[2.3.1 - Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_grcnether-build1.jar)
[2.3.1 - Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_grcnether-build0.jar)

### CODE REVIEW

**Comment by Ar97x** [comment]
I'm seriously more hyped to Nether Module, it'll be way more fancy than
Desert Module, I think.

**Comment by labpaw** [comment]
Are Nether plants will grow only in Nether? I think it should be so if you are not implemented it yet (just asking, didn't checked that).

**Comment by IceDragon200** [comment]
@Adaptivity Currently you can just grab soul sand and plant them, anywhere

**Comment by Sunconure11** [comment]
In the future, should we continue working on this again, or should we rebuild it?

**Comment by Ar97x** [comment]
I was very excited for this when it was started, I say it should be our
major concern for the next release (after 2.5)

**Comment by Sunconure11** [comment]
It would need to be recoded, but, I suppose it could be done then

**Comment by Sunconure11** [comment]
When this gets more complete, would it be possible to create a build with this, milk, and all of the other modules?

**Comment by Sunconure11** [comment]
I'll create textures for the fuel crop later, since there were a few additions. The mob might come last.

**Comment by IceDragon200** [comment]
@Sunconure11 So we'll move this to a new mod of its own, come with a name later when we revisit it :)

**Pull request closed without merging**
