### PR TITLE
2.6.0 Changes

### LINKED ISSUE #361: Assertion error
http://pastebin.com/rcs6XxSK

### LINKED ISSUE #363: TagParser error
http://pastebin.com/5NP437iR

And I thought the weird issues were over.

### LINKED ISSUE #367: Division by zero error when trying to view fermenting recipes
http://pastebin.com/N8xBQHA4

I press SHIFT + R on origin yeast, and this happens.

Also, the latest build appears to be down.

### PR DESCRIPTION
**Pull request by IceDragon200**
### Latest

**2016-05-19 @ 15:01:24 EST** 6c25b91 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--6c25b91.jar)

> #### Checksums
> 
> **MD5**: 5ff595b07d3a621714c3c733929e221f
> **SHA1**: ccc6d290058f60972567cee61071fd8252c03f89
> **SHA256**: 3e6c52ec61e0f6e20eb8e8f79a612a3dae5de25bb5251e1d0123cdcb5e2c9626
> #### Changes
> - Default to `rennetSource` items for Rennet brewing recipes (@Sunconure11)
### Old

**2016-05-18 @ 08:27:56 EST** b5722b1 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--b5722b1.jar)

> #### Checksums
> 
> **MD5**: a15f654a96d3d65241b28123a96fc329
> **SHA1**: 7a413bca4ae93f5971fdb44a317789786a3ecd32
> **SHA256**: 90406b7dc5a35fb83f4711afb54a05f5c926a37d419055d285b8780f7cf7635b
> #### Changes
> - Changed Brewer and Apiarist Villager IDs

**2016-05-14 @ 18:47:46 EST** 6ddebaa [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--6ddebaa.jar)

> #### Checksums
> 
> **MD5**: 85137c92c04ad20a8b1747ff51a5461b
> **SHA1**: 0d7060fb1805a9f831bd4a10c179bb9d052b9d86
> **SHA256**: fbdb094deb93215f94c69efd5187f183423d3648a43e593241ade305d29965bd
> #### Changes
> - Various fixes found while porting to MC 1.8, and then back ported to MC 1.7, don't ask when the 1.8 port will be finished.

**2016-05-11 @ 14:13:19 EST** d83668d [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--d83668d.jar)

> #### Checksums
> 
> **MD5**: 4232151b978313ebe153d12c6fe8250e
> **SHA1**: 27b929a8e1c4c6804ea3d4a7ac7e24b35f2364d0
> **SHA256**: c96f17adee83501648c4182067edc9f5027346e215d8ef93c9b3096b5462f378
> #### Changes
> - Fixes #367

**2016-05-10 @ 14:48:09 EST** 847b5a7 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--847b5a7.jar)

> #### Checksums
> 
> **MD5**: e4a0dbed5a1ea8308d879337c9a25fc5
> **SHA1**: eb175f0f047008bacc4e77c71dcb757a7834dda7
> **SHA256**: 9397fa73e20d4aea964f1810a907ed8d39a623bdae632526cd2e1f20e6b2db42

**2016-05-10 @ 10:53:08 EST** b4d3331 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--b4d3331.jar)

> #### Checksums
> 
> **MD5**: b63ca06dd721aa12e9a4c62a19627d3c
> **SHA1**: 6039930f634cf98d787df66264eb59f844ddbd5e
> **SHA256**: 6029fb88ff7768af3804a2727b0392c19ca3968fc4aac8549ab6e3a4a66e6e23
> #### Changes
> - Finally Fixed Thistle World Gen
> - Added Multi Tags, allow you to specify batches of biome types:
> 
> ```
> +MOUNTAINS;+HILLS,-SNOWY,-COLD
> ```
> - Refactored Bucket Handler code (no more SpecialBucketHandler)

**2016-05-08 @ 12:08:49 EST** 9f7c31d [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--9f7c31d.jar)

> #### Checksums
> 
> **MD5**: 48149b1cfcda9f93e7ff39ad3d662527
> **SHA1**: 576d3831dc4a603e541b0af1f3209e40c1751002
> **SHA256**: 349866fc2d4a4e015a944346799aa0eeca5e9179bd47f5846e86a74325c900cc
> #### Changes
> - Fixes #363
> - Fixes edge case with InventoryProcessor#slotsAreValid where the slot id was greater than or equal to the inventory size

**2016-05-07 @ 22:22:20 EST** 959d5c0 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--959d5c0.jar)

> #### Checksums
> 
> **MD5**: 9fb713c2a7f291ab988913bae232a0a4
> **SHA1**: baf7f7afc9a6f18b83c0405eb760c1053ea94cd4
> **SHA256**: b9f14bfc96357d9a562c978f8c035c1c8deca132d1d952b3f049f5a288fd36bb
> #### Changes
> - Refactored Biome Gen config options, using [TagParser format](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/General-Information#config-tags-effective-in-26x)

**2016-05-07 @ 19:34:49 EST** d451bd4 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--d451bd4.jar)

> #### Checksums
> 
> **MD5**: 5be15a25b74651473603b9290037fbb4
> **SHA1**: 0e3efaba41bcfc21376d99149ec51f3eb63eb631
> **SHA256**: 4148c9aaa60d7576862ba129cfb24a75823edb9b114551a5de08eb6edb4708a8
> #### Changes
> - Milk, Butter Milk, Skim Milk, Whey (bottles) should now be edible/drinkable

**2016-05-07 @ 18:05:08 EST** 0bbe3b8 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--0bbe3b8.jar)

> #### Checksums
> 
> **MD5**: 3c937ba29588f2febe5ad5487bf69cc7
> **SHA1**: 2b3a327fca325e3853155ed8e486a65c1541ce77
> **SHA256**: 4469ba539bc13905e6c7d21006910e629281eb73fc2dc796d6a7b21f7d4caac9
> #### Changes
> - Fixed _Mumbles_ trying to serialize a item stack _Mumbles_, fixes #361

**2016-05-07 @ 15:40:54 EST** db39760 [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--db39760.jar)

> #### Checksums
> 
> **MD5**: 7a33bb776ed4a43078f328a52ce89b2c
> **SHA1**: 2f685114e6e09ff115815c92580f1c294382e22a
> **SHA256**: e3638e1a9b8a385cbfd8df3a422626828cc0928f8f260a894ef02424527836d1
> #### Changes
> - Maybe User Configs will stop crashing now? (despite my judgement)

**2016-05-06 @ 09:27:38 EST** 62db41f [2.6.0 - Download](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.6.0/growthcraft-1.7.10-2.6.0-complete--62db41f.jar)

> #### Checksums
> 
> **MD5**: 1755c13973a456d48f81f2221a112076
> **SHA1**: a1f50b3e60993f7f48b3627703ba802203ffa80d
> **SHA256**: 64c2b2f2ea63659419e82b931cc01a28d29fa7b8037524c29e39db16489696c8
> #### Changes
> - JSON Configs now allow nulls
## Super Old Builds

Really? You want something really old?
You can pick up all the older test builds (starting from 2.1.0 up to 2.5.2)
[Mediafire - Older Builds](https://www.mediafire.com/folder/8pmaoyycz9jjd/Builds)
## Fixes / New Features
- #306 - Salt Bucket duplication bug
- #311 - Thistle spread logic was broken
- #322 - Critical bug with `FluidHandler` blocks causing a refresh when nothing changed
- #326 - Ricotta bowls are configurable 
- #346 - Thistle tick rate restored
- #349 - "Young" Booze was renamed
- #358 - Fluid got a major overhaul with the addition of Fluid Container based crafting recipes
- #360 - Config option for changing Vanilla bottle behvaiour (making it a container and setting its contents to 333mB)
- #361 - Fixed serialization errors with MultiFluidStackSchema and ItemStacks
- #362 - Milk, Skim Mlk, Butter Milk and Whey bottles are now drinkable
- #363 - Tags for specifying biome types
- All booze recipes have been updated to use ore dictionary or fluid dictionary items and fluids.
- Yeast Types have been registered as Ore Dictionary items now:

```
Brewers - yeastBrewers
Origin - yeastOrigin
Ethereal - yeastEthereal
Bayanus - yeastBayanus
Lager - yeastLager
```
- The Amazing Stick is no more, instead use a Crowbar, and do the same thing
- Rather broken support, but still support Brew Kettle, Fruit Press and Fermenting Barrel recipes in NEI 
- Fermenting Barrels should now drop with their fluid content if broken with a IToolWrench item (Buildcraft Wrenches or Growthcraft Crowbars)
- Cheese Press can now be toggled via redstone
  - Added 2 new config options to growthcraft/milk.conf (Device/Cheese Press)
    - "Redstone Operated" - should the block be toggled via redstone? (this may break the Hand Operation)
    - "Hand Operated" - should the block be toggled by hand? (may not work as expected with Redstone Operated)
- Cheese recipes now accept `materialSalt`
- Added `bucketSalt`, `bottleSalt`, `bottleSaltwater`, and `bucketSaltwater` ore dictionary entries
- Cheese Vat should now accept cheese ingredients in any order
- Cheese Blocks now drop their slices upon breaking (like they are SUPPOSE TO.)
- Added Salt Blocks
- Fixed MAJOR fluid handling bug - All fluid handler blocks would trigger a refresh regardless of if the fluid was drained or filled if they used the FluidTanks interface
- Bees module fixes, including Forestry Fluid names by @SimonMeskens 
- Updated pt_BR lang by @Ar97x 
- User Configs now allow `null`s
- Fixed edge case with InventoryProcessor#slotsAreValid where the slot id was greater than or equal to the inventory size

### CODE REVIEW

**Comment by IceDragon200** [comment]
Due to the number of core changes, we can do a minor release, instead of a teeny release, all modules planned will be pushed to 2.7 instead

**Comment by killerjdog51** [comment]
so what does the crowbar do? what is it used for?

**Comment by IceDragon200** [comment]
@killerjdog51 It replaces "The Amazing Stick", which in turn is our implementation of Buildrcraft's wrench.

It's functions:
- Rotate Blocks
- Pop Blocks to maintain state

**Comment by killerjdog51** [comment]
@IceDragon200 I see. Thats a pretty good addition. I'm guessing you use it on the cellar blocks, like the fermentation barrel, fruit press, brew kettle, cheese vat, etc?

**Comment by IceDragon200** [comment]
@killerjdog51 That is correct :)

**Comment by Alatyami** [comment]
Per chat, we are going to queue this up for release. Thank you for all your hard work @IceDragon200 !

**Pull request merged**
