### PR TITLE
Update zh_CN.lang(s)

### PR DESCRIPTION
**Pull request by 3TUSK**
I have tested those translation in-game in order to make sure that they are suitable translation.
btw thank you guys for updating growthCraft to 1.7.10!

### CODE REVIEW

**Comment by Sunconure11** [comment]
Looks good to me, but, what about everyone else?

**Comment by 3TUSK** [comment]
~~_everyone else_? Like, what?~~
Never mind this comment.

**Comment by IceDragon200** [comment]
@3TUSK Looks good to me, but do you mind prefixing the commits with the module they modify

Use `all*` if you modified too many modules to bother listing, sorry if I'm being fussy...

`all*: Update zh_CN.lang`

**Comment by 3TUSK** [comment]
Well... f4c8dad76b2f2359bc0dc36733accad7edb073b2 this commit did update all modules' translation to latest version because I want to make things clean. Do you mean that I need to prefix those two commits with module name? If I understand wrongly please don't mind.

**Comment by IceDragon200** [comment]
@3TUSK Yes, prefix the commit messages with the module they modify next time, I'll merge this so don't worry about it this time. Thanks for you contribution to GrowthcraftCE :+1:

**Comment by 3TUSK** [comment]
Well, I won't forget next time. :+1:

**Comment by Sunconure11** [comment]
@3TUSK Would you be able to create Chinese translations for the new content that has been added to this mod since this pull?

**Pull request merged**
