### PR TITLE
Additional village structures

### PR DESCRIPTION
**Pull request by IceDragon200**
@Ar97x Lets see if we can get these structures in
- [x] Rice Field ([Screenshot](https://dl.dropboxusercontent.com/u/72618186/screenshots/Minecraft/2015-08-11_12.06.38.png))
- [ ] Bamboo ***(?)
- [ ] Apple **\* (?)

Also I'm a bit undecided on the structure generate method I chose, currently I use a 3d Array (Array<Array<String>>) with a schema of the structure:

``` java
// ...
    static final String riceFieldSchema[][] = {
        {
            "x         x",
            " x-------x ",
            " |ppppppp| ",
            " |pwwwwwp| ",
            " |pwpppwp| ",
            " |pwpppwp| ",
            " |pwpppwp| ",
            " |pwwwwwp| ",
            " |ppppppp| ",
            " x-------x ",
            "x    |    x",
            "    sss    "
        },
// ...
```

This method allows me to specify blocks with metadata and perform really tedious design, vs lines upon lines of `fillWithBlocks` and calculating offsets and ... (_internal screaming_).

### CODE REVIEW

**Comment by Ar97x** [comment]
Do it the way it's best for you, cause Idk almost nothing about programming, I just know how to use and make schematics. I'll see if I can make an apiary model today.

**Comment by IceDragon200** [comment]
@alatyami Noooooooooooooooes don't merge just yet!
;-; I wasn't finish, I opened the pr for discussion!

**Comment by Alatyami** [comment]
Doh! Saw the pull request and jumped on it ... time for our first regression :)

**Comment by Alatyami** [comment]
Pull Request reverted

**Comment by IceDragon200** [comment]
Well.. looks like I'll need to create another one then :3

**Comment by Alatyami** [comment]
Sorry about that ... I'm used to Pull Requests being merge ready.

**Pull request merged**
