### PR TITLE
Silenced those annoying javadoc warnings

### PR DESCRIPTION
**Pull request by IceDragon200**
For #54

Wallaaaaa, I ~~killed~~ fixed em all!

PS.
I'm going to have to get used to merging to development instead of master... (had to cherry-pick after noticing)

### CODE REVIEW

**Comment by Ar97x** [comment]
Seriously? That is a great improvement, I don't play without Waila anymore =D

-------- Mensagem Original --------
De:Corey Powell notifications@github.com
Enviado em:Sat, 29 Aug 2015 10:52:55 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Assunto:[Growthcraft-1.7] Silenced those annoying javadoc errors (#70)

**Comment by IceDragon200** [comment]
@Ar97x Not WAILA, WALLAH (as in the expression), or tadah, ya know?

But yeah, those warnings usually distract me during builds "uggh, where is that error, oh gawd warnings"

**Comment by Sunconure11** [comment]
Should I accept this?

**Comment by IceDragon200** [comment]
@alatyami @Sunconure11 Merge if its A.OK, I'm pretty much done with it

**Comment by Ar97x** [comment]
Hahahahahha I never heard that, so what came to my head is that you fixed Waila

-------- Mensagem Original --------
De:Joseph Caleb Jones notifications@github.com
Enviado em:Sat, 29 Aug 2015 17:04:18 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Cc:Ar97x vdiehl97@gmail.com
Assunto:Re: [Growthcraft-1.7] Silenced those annoying javadoc warnings (#70)

**Comment by IceDragon200** [comment]
@Ar97x You could probably open an issue for it?

**Comment by Ar97x** [comment]
I think we already have one for Compatibility. I'll put you into it

**Pull request merged**
