### PR TITLE
Waila handlers

### PR DESCRIPTION
**Pull request by IceDragon200**
For #96 
Looking for feedback and testers, pls halp?

[Screenshots](https://www.dropbox.com/sh/76chacjbpfl6av9/AAArEq3cWAHI5M8KIBbFUA2Va?dl=0)
### Latest

[Build 4](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_waila-handlers-build4.jar)
### Old

[Build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_waila-handlers-build3.jar)
[Build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_waila-handlers-build2.jar)
[Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_waila-handlers-build1.jar)
[Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_waila-handlers-build0.jar)

### CODE REVIEW

**Comment by spannerman79** [comment]
I hope Waila is a soft/optional dependency and not a hard one.

**Comment by IceDragon200** [comment]
@spannerman79 Its an soft/optional dependency

**Comment by IceDragon200** [comment]
@alatyami, @spannerman79, @Adaptivity I believe I'm finished with this, unless you guys have any changes you'd like

**Comment by labpaw** [comment]
Looks good :+1:

**Comment by Sunconure11** [comment]
So, ready to merge then?

**Pull request merged**
