### PR TITLE
Fluid blocks

### PR DESCRIPTION
**Pull request by IceDragon200**
For #52 
Looking for testers and folks who like breaking stuff
A bit rough around the edges and a few bugs here and there, but its a fair (re-)start
## What does this do?

Changes growthcraft's internal bucket item to an actual ItemBucket and not some hacky Item, in addition to adding fluid blocks for, the fluids, this also introduces the BucketHandler (swiped from buildcraft), for handling bucket fills (so we can pick up that sake you spilt all over the floor)

Some additions are hiding certain items in NEI
### Latest

[Build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_fluid-blocks-build3.jar)
### Old

[Build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_fluid-blocks-build2.jar)
[Build 1](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_fluid-blocks-build1.jar)
[Build 0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_fluid-blocks-build0.jar)

### CODE REVIEW

**Comment by IceDragon200** [comment]
@alatyami Well that's all the fluid blocks I believe, now if I could get some ~~minions~~ folks willing to test this

**Comment by labpaw** [comment]
Going to run some tests as I requested this :)

**Comment by IceDragon200** [comment]
@Adaptivity  Yay a ~~minion~~ tester, lemme know if anything breaks :D I'll fix as fast as I can

**Comment by labpaw** [comment]
Notes during testing:
1) All fluid blocks in NEI have tile.null.name names. Also, fluid blocks should be in GC creative tab but they aren't there.
2) Deprecated buckets are available in NEI and in creative tabs. You should hide them. NEI has an API function to hide blocks/items from it (API.hideItem(new ItemStack());) Also, there are few blocks that should be hidden from NEI. I'll create another issue for it later.
3) Fluid blocks have same textures in inventory. Is this intentional?
4) Apple Cider, Mead and Wine can be poured in OpenBlocks tank and TE portable tank. But Ale and Sake can't be poured in tanks.
5) Wooden Bucket voids/destroys GC fluids.
6) Deprecated tooltip localization hardcoded. Low priority but still.

**Comment by IceDragon200** [comment]
@Adaptivity Sorry about the late-ish reply, I'm currently repairing my wall (don't even ask why)
- 1 f forgot they needed a name, 
- 2 (only for creative tabs, NEI will be done once the WAILA integration is merged)
- 3 it was a ItemBlock issue, not sure if I fixed 
- 4 though ALL the fluids inherit from the same base, so they should work, 
- 5 Not sure how to fix this one ;O Related https://github.com/alatyami/Growthcraft-1.7/issues/52#issuecomment-131791690 
- 6 Still haven't fixed that, sorry :cry: 

Added a new build

**Comment by labpaw** [comment]
:+1: For point 5 I think we need to ask @DarkGuardsman what we should do. Dear @DarkGuardsman, what GC should do now to support Wooden Buckets? Maybe you can add compatibility on your end or GC fluid code still miss something? Current code available at this branch: https://github.com/alatyami/Growthcraft-1.7/tree/fluid-blocks

1) Fixed. Tested.
2) Partially fixed. Will flow into another issue.
3) Fixed. Tested.
4) Fixed. Tested.
5) Not an issue. This is my fault :)
6) Should be easy to fix and very minor thing :smile:

**Comment by DarkGuardsman** [comment]
Are you using the lastet version of Wooden Buckets? As the only way for a fluid to be voided is if it is not registered, or registered with a fluid block. In which it may be able to pick up the fluid but can't place the fluid.

**Comment by labpaw** [comment]
I'm using WoodenBucket-1.7.10-0.0.3b5.jar and tried GC test build 0 and 1 with new fluid code. Wooden Bucket voids all GC fluids from the ground and even from fluid containers (like OpenBlocks tank)

**Comment by DarkGuardsman** [comment]
Another question, are you in creative mode? as the bucket is designed to void in creative mode if empty.

**Comment by labpaw** [comment]
Heh, this is my fault then. Didn't knew about that feature :) Now it's working, thanks for your help. Also, what do you think about custom textures with better fluid color for GC fluids similar to which you made for Buildcraft and Tinkers Construct?

**Comment by DarkGuardsman** [comment]
I could add some custom textures for GC fluid buckets. Its a very easy process as I just have to make a new overlay per fluid. Though, I am working on a way to automate this so every mod doesn't need a custom texture set.

**Comment by labpaw** [comment]
Cool. I think you shouldn't waste your time making textures then since it's a minor thing. Better spend all the time coding automation process. :smile: Good luck in it :+1:

**Comment by DarkGuardsman** [comment]
Na it doesn't take too much time and is a good de-stresser. Plus hand made textures look so much nicer than anything I can do with automation. 

Also https://github.com/BuiltBrokenModding/SingleBlockMods/commit/d50c5f8f52c15711570d09f88ab5a05569672929

**Comment by IceDragon200** [comment]
@Adaptivity Fixed #100 as well

I forgot to change branches when I did the fix, so I'll just merge it with the fluid blocks

New build (Build 2)

@DarkGuardsman Thanks for the fix :smile:

**Comment by IceDragon200** [comment]
@Adaptivity Updated redid it, look at https://github.com/alatyami/Growthcraft-1.7/commit/cec531271ad4a5a6d38be561a06a564e82048fe7 is this is ok?

**Comment by labpaw** [comment]
Yeah, it's good.

**Comment by IceDragon200** [comment]
@alatyami @Sunconure11 All seems to be well, you can merge this now

**Pull request merged**
