### PR TITLE
Growthcraft 2.5.0 Release

### PR DESCRIPTION
**Pull request by IceDragon200**
:gift:

### CODE REVIEW

**Comment by Alatyami** [comment]
Can you increment the version number in the gradle.properties to 2.5.0.  That should be the only place remaining to bump up the version number for Travis-CI.

**Comment by IceDragon200** [comment]
@Alatyami It was incremented when we started doing Forestry support ourselves, also we still have a few bugs in the pipeline being addressed.

**Comment by Alatyami** [comment]
Think we are ready to merge and release?

**Comment by IceDragon200** [comment]
@Alatyami Yeah, I think we can release now, if anything comes up, we'll do a patch release afterwards

**Comment by Alatyami** [comment]
If we merge this with master, then we'll need to rebase development. Nevermind, just got my branches sync'd.

**Pull request merged**
