### PR TITLE
Additional village structures (take 2!)

### PR DESCRIPTION
**Pull request by IceDragon200**
Continuation of #31
- [x] Rice Field ([Screenshot](https://dl.dropboxusercontent.com/u/72618186/screenshots/Minecraft/2015-08-11_12.06.38.png))
- [x] Bamboo Yard
- [x] Apple Farm (because I'm terrible at naming)
- [x] Apiarist (Beekeeper Village Structure)

Test build for anyone interested :3
[Growthcraft 2.2.1 + Additional Village Structures Build 6](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/growthcraft-2.2.1-avs6.jar)

_NOTE_ You must enable the generation of these new structures, Hops and Grape Vineyards are generated as normal.

``` shell
# config/growthcraft/apples.conf
general {
    B:"Generate Village Apple Farms"=true
}

# config/growthcraft/bamboo.conf
general {
  B:"Generate Village Bamboo Yard"=true
}

# config/growthcraft/bees.conf
general {
  B:"Spawn Village Apiarist Structure"=true
}

# config/growthcraft/rice.conf
general {
  B:"Generate Village Rice Fields"=true
}
```

### CODE REVIEW

**Comment by Ar97x** [comment]
Don't you like the stairs effect? I think that they give a good aspect to
the building. But I'll give it a try soon, I should have a response later.
Em 11/08/2015 20:21, "Corey Powell" notifications@github.com escreveu:

**Comment by IceDragon200** [comment]
@Ar97x Its not like I didn't like them, its the coding, I'd need to figure out all the metadata for their rotation and flipping it upside down, planks are so much easier ;_;

**Comment by Ar97x** [comment]
Oh I get it. I'll change it when I get home.

**Comment by Alatyami** [comment]
Looks good to me ... for the future remember to do pull requests to the development branch that way if it does break the build then we are not affecting the release branch.

**Comment by Ar97x** [comment]
The link is broken :( I have some time now, so I will try to bring the
Apiary and the new Bamboo Yard quick.

2015-08-12 8:22 GMT-04:00 Alatyami notifications@github.com:

**Comment by Ar97x** [comment]
Thinking about the apiary, I had an idea. What about an apiarist villager? Trading Emeralds for Honeycombs/Bees and Flowers for Emeralds? Anybody up for it?

**Comment by Alatyami** [comment]
I thought that there already was one ...

**Comment by Ar97x** [comment]
From Forestry I'm pretty sure there is, but on GC I don't see any.

2015-08-12 16:06 GMT-04:00 Alatyami notifications@github.com:

> I thought that there already was one ...
>

**Comment by Ar97x** [comment]
https://www.dropbox.com/s/27505ok9a81q2lx/GRC-Bees.schematic?dl=0 Fixed
Bamboo Yard and released the Apiary schematics. I would like a feedback
from contributors, positive or negative, suggestions are always welcome.

2015-08-12 16:24 GMT-04:00 Victor Diehl vdiehl97@gmail.com:

> From Forestry I'm pretty sure there is, but on GC I don't see any.
> 
> 2015-08-12 16:06 GMT-04:00 Alatyami notifications@github.com:
> 
> > I thought that there already was one ...
> >

**Comment by Sunconure11** [comment]
Is it okay to merge this?

**Comment by Ar97x** [comment]
I don't think so. We may have somethings to discuss yet.

**Comment by Alatyami** [comment]
@IceDragon200 are you ready for peer review or are you still working on this?

**Comment by IceDragon200** [comment]
@alatyami @Ar97x @Sunconure11 I'll add the Apiary village structures and then we can review, unless there are more suggestions :3

Fixed the link as well

As for the villager, it seem  there are only cases for selling `Honey Mead` currently,
how about we discuss how many emerald cost for honey combs and bees, since its mostly adding a few new lines to the Village Handler

**Comment by IceDragon200** [comment]
@Ar97x Okay, I've added the Apiary/ist structure, I tweaked your tree a bit, also the schema didn't seem to include any of the Bee related structures so I just threw something where it felt like it fit. 

@alatyami I believe I'm finished, you start the review process

I've also updated the download link with the latest test build

**Comment by Ar97x** [comment]
Great, I'll give it a shot now

**Comment by Ar97x** [comment]
About the apiarist villager lines, I think something about 3-5 bees or 7-12
honeycombs per emerald. and 1 emerald for 30-40 flowers is fair enough.

2015-08-12 21:52 GMT-04:00 Victor Diehl vdiehl97@gmail.com:

> Great, I'll give it a shot now

**Comment by Alatyami** [comment]
Compiles 😎

**Comment by IceDragon200** [comment]
@alatyami :3 I test build before any and every push

@Ar97x _soft_ I kinda set it 5+ emeralds for 1 bee, I forgot we aren't dealing with forestry level bees...

**Comment by Ar97x** [comment]
Crashed
https://www.dropbox.com/s/fo1sit892lsfvzh/crash-2015-08-12_22.41.23-server.txt?dl=0

2015-08-12 22:24 GMT-04:00 Corey Powell notifications@github.com:

**Comment by IceDragon200** [comment]
@Ar97x Fixed, (I think), updated the download link again

**Comment by Ar97x** [comment]
Just a little tweaks and we can merge this. I wanna know how the apiarist
looks like (I think a bee protection vest [Idk the right name] might look
pretty nice). And if possible, you should make it spawn inside that little
balcony I built in the apiary. And the bee box is suposed to be outside,
with the flowers and the tree. The bee hive looks cool there. Can you model
again the tree? Make it look like a vanilla oak and it's just fine.

**Comment by IceDragon200** [comment]
@Ar97x I kinda liked the 3x3x3 cubey tree, but I agree it needs to look more natural, also for the apiarist villagerm I copied the brewers texture and colored it orange.
Also I forgot to spawn the villagers in question, that's been fixed now though.

All the schemas where upside down!
So the entrance to the stuctures was at the back, you'd realize it when you walk on the gravel path in the village.

Updated build again as well, this should be the final one (I hope)

**Comment by Ar97x** [comment]
Everything is okay for me. The villager and the structures are spawning correctly, I just wish that the villagers spawn behind the little counter, but that's fine for me. If there isn't anything to be added, we are ready to merge.

**Comment by Alatyami** [comment]
@IceDragon200 ... Anything else left? This will be version 2.2.2 along with the gradle update.  Then we can post it to the forums.

**Comment by IceDragon200** [comment]
@alatyami Onwards to merge city!

**Comment by Alatyami** [comment]
Got it merged in ... waiting on Travis-CI to publish the artifact to the release notes.

**Pull request merged**
